#**Question 6.**

**We will estimate the test error of logistic regression model using the validation set approach.
Suppose we use logistic regression to predict the probability of default using income and balance on the
Default data set.**

**a. Fit a logistic regression model that uses income and balance to predict default. Provide a summary of the
model and interpret the results.**

In [ ]:
import pandas as pd
import numpy as np
import patsy
import seaborn as sns
import matplotlib.pyplot as plt

import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# statsmodels issue: https://github.com/statsmodels/statsmodels/issues/3931
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

sns.set(style="white")
%matplotlib inline

In [ ]:
np.random.seed(1)

df = pd.read_csv("Default.csv", index_col=0)

df['default_yes'] = (df['default'] == 'Yes').astype('int')
df.head()


<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   default      10000 non-null  object 
 1   student      10000 non-null  object 
 2   balance      10000 non-null  float64
 3   income       10000 non-null  float64
 4   default_yes  10000 non-null  int64  
dtypes: float64(2), int64(1), object(2)
memory usage: 468.8+ KB


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   default      10000 non-null  object 
 1   student      10000 non-null  object 
 2   balance      10000 non-null  float64
 3   income       10000 non-null  float64
 4   default_yes  10000 non-null  int64  
dtypes: float64(2), int64(1), object(2)
memory usage: 468.8+ KB


In [ ]:
lr = LogisticRegression(C=10**6, tol=1e-6)
X = df[['income', 'balance']]
y = df['default_yes']
mod = lr.fit(X, y)
mod.coef_

array([[2.08089755e-05, 5.64710295e-03]])

**a. Fit a logistic regression model that uses income and balance to predict default. Provide a summary of the
model and interpret the results.**

In [ ]:
f = 'default_yes ~ income + balance'
res = smf.logit(formula=f, data=df).fit()
res.summary()

Optimization terminated successfully.
         Current function value: 0.078948
         Iterations 10


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:            default_yes   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Mon, 24 Mar 2025   Pseudo R-squ.:                  0.4594
Time:                        02:08:28   Log-Likelihood:                -789.48
converged:                       True   LL-Null:                       -1460.3
Covariance Type:            nonrobust   LLR p-value:                4.541e-292
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -11.5405      0.435    -26.544      0.000     -12.393     -10.688
income      2.081e-05   4.99e-06      4.174      0.000     1.1e-05    3.06e-05
balance        0.0056      0.000     24.835      0.000       0.005       0.006
==============================================================================

Possibly complete quasi-separation: A fraction 0.14 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

**b. Using the validation set approach, estimate the test error of this model. In order to do this, you must perform
the following steps:**

**b.a. Split the sample set into a training set and a validation set.**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7)


**b.b. Fit a multiple logistic regression model using only the training observations.**

In [ ]:
mod = lr.fit(X_train, y_train)
mod.coef_

array([[1.94345652e-05, 5.16830969e-03]])

**b.c. Obtain a prediction of default using the validation set.**

In [ ]:
y_pred = mod.predict(X_test)
print(y_pred)

[0 1 0 ... 0 0 0]


**b.d. Compute the validation set error, which is the fraction of the observations in the validation set that
are misclassified.**

In [ ]:
1-(y_pred == y_test).mean()

np.float64(0.025857142857142912)

**c. Repeat the process in (b) three times, using three different splits of the observations into a training set and a
validation set. Comment on the results obtained.**

In [ ]:
for i in range(1,4):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7)
    mod = lr.fit(X_train, y_train)
    print("--------------------------------")
    print(mod.coef_)
    y_pred = mod.predict(X_test)
    print(y_pred)
    print(i, (y_pred == y_test).mean())

NameError: name 'train_test_split' is not defined